pipeline {
    agent any
    tools {
        maven 'Maven'
//        jdk 'jdk8'
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }

        stage ('Build') {
            steps {
                dir('harvester/gss-modules')
                    {
                    sh 'mvn -B clean package'
                    }
            }
            post {
                always {
                    junit allowEmptyResults: true, testResults: 'target/surefire-reports/**/*.xml'
                    }
            }
        }
        stage('Deploy JAR to the Flink'){
            steps{
                dir('harvester/gss-modules/gss-telemetry-emulator/target')
                {
                sh 'curl -X POST -H "Expect:" -F "jarfile=@gss-telemetry-emulator-1.0-SNAPSHOT.jar" http://13.82.175.57:8085/jars/upload'
                }
            }
        }
    }
}