package com.cnhindustrial.telemetry.common.model;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Autogenerated code Controller Data transfer object. To be reviewed.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Field implements Serializable {

    private static final long serialVersionUID = 3101110630948685672L;

    @JsonProperty("@Id")
    private String id;
    @JsonProperty("Description")
    private String description;
    @JsonProperty("FieldBoundaries")
    private List<Object> fieldBoundaries = null;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new HashMap<>();

    @JsonProperty("@Id")
    public String getId() {
        return id;
    }

    @JsonProperty("@Id")
    public void setId(String id) {
        this.id = id;
    }

    @JsonProperty("Description")
    public String getDescription() {
        return description;
    }

    @JsonProperty("Description")
    public void setDescription(String description) {
        this.description = description;
    }

    @JsonProperty("FieldBoundaries")
    public List<Object> getFieldBoundaries() {
        return fieldBoundaries;
    }

    @JsonProperty("FieldBoundaries")
    public void setFieldBoundaries(List<Object> fieldBoundaries) {
        this.fieldBoundaries = fieldBoundaries;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder().append(description).append(fieldBoundaries).append(id).append(additionalProperties).toHashCode();
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if (!(other instanceof Field)) {
            return false;
        }
        Field rhs = ((Field) other);
        return new EqualsBuilder().append(description, rhs.description).append(fieldBoundaries, rhs.fieldBoundaries).append(id, rhs.id).append(additionalProperties, rhs.additionalProperties).isEquals();
    }

}
