version: "3"
services:
  jobmanager:
    image: flink:latest
    container_name: jobmanager
    expose:
      - "6123"
    ports:
      - "8085:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - EVENT_HUB_TELEMETRY_ENDPOINT=Endpoint=sb://cnh-bdgs-namespace.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=yJmQ4/3L9n58crTYQdZnElEbHMTYmXKf03mzHI7SvwA=;EntityPath=cnh-bdgs-dev

  taskmanager:
    image: flink:latest
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager